/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingShopRouteImport } from './routes/onboarding.shop'
import { Route as OnboardingRewardRouteImport } from './routes/onboarding.reward'
import { Route as OnboardingFeaturesRouteImport } from './routes/onboarding.features'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingShopRoute = OnboardingShopRouteImport.update({
  id: '/onboarding/shop',
  path: '/onboarding/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRewardRoute = OnboardingRewardRouteImport.update({
  id: '/onboarding/reward',
  path: '/onboarding/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFeaturesRoute = OnboardingFeaturesRouteImport.update({
  id: '/onboarding/features',
  path: '/onboarding/features',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding/features': typeof OnboardingFeaturesRoute
  '/onboarding/reward': typeof OnboardingRewardRoute
  '/onboarding/shop': typeof OnboardingShopRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding/features': typeof OnboardingFeaturesRoute
  '/onboarding/reward': typeof OnboardingRewardRoute
  '/onboarding/shop': typeof OnboardingShopRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding/features': typeof OnboardingFeaturesRoute
  '/onboarding/reward': typeof OnboardingRewardRoute
  '/onboarding/shop': typeof OnboardingShopRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding/features'
    | '/onboarding/reward'
    | '/onboarding/shop'
    | '/onboarding/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding/features'
    | '/onboarding/reward'
    | '/onboarding/shop'
    | '/onboarding/welcome'
  id:
    | '__root__'
    | '/'
    | '/onboarding/features'
    | '/onboarding/reward'
    | '/onboarding/shop'
    | '/onboarding/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingFeaturesRoute: typeof OnboardingFeaturesRoute
  OnboardingRewardRoute: typeof OnboardingRewardRoute
  OnboardingShopRoute: typeof OnboardingShopRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/shop': {
      id: '/onboarding/shop'
      path: '/onboarding/shop'
      fullPath: '/onboarding/shop'
      preLoaderRoute: typeof OnboardingShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/reward': {
      id: '/onboarding/reward'
      path: '/onboarding/reward'
      fullPath: '/onboarding/reward'
      preLoaderRoute: typeof OnboardingRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/features': {
      id: '/onboarding/features'
      path: '/onboarding/features'
      fullPath: '/onboarding/features'
      preLoaderRoute: typeof OnboardingFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingFeaturesRoute: OnboardingFeaturesRoute,
  OnboardingRewardRoute: OnboardingRewardRoute,
  OnboardingShopRoute: OnboardingShopRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
